config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get :help, to: 'static_pages#help'
  get :signup, to: 'users#new'
  get :problem_search, to: 'problems#problem_search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :likes, to: 'likes#index'
  post   "likes/:post_id/create"  => "likes#create"
  delete "likes/:post_id/destroy" => "likes#destroy"
  resources :comments, only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :messages
    end
  end
  resources :messages,            only: [:create, :destroy]
  resources :notifications, only: :index
  resources :problems
  resources :problem_comments, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.page(params[:page]).per(10)
    end
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<% provide(:title, "チルシェアとは？") %>
<h1>チルシェアとは？</h1>

app/views/static_pages/home.html.erb
<% if logged_in? %>
      <div id="carousel-2" class="carousel slide carousel-fade" data-ride="carousel" data-interval="6000">
    <div id="top-post-page">
        <div class="login-top-image">
            <%= image_tag asset_path("double.jpg", alt: "responsive image"), class: "d-block image-fluid w-80" %>
            <h1>育児や妊娠時にオススメなこと・ものはありませんか？<br>
            投稿してみんなで共有しよう！！！！</h1>
            <h2>もし悩みを抱えていたり、聞いて欲しいことがあるなら<br>
            悩みの場で信用できるフォロワーのみんなに解決してもらおう！<br>
            <li><%= link_to '悩みの場にGo！！', problems_path, class: "link-color-go" %></li></h2>
        </div>
    </div>
    </div>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= render 'posts/search' if logged_in? %>
      <p class="p-post"><%= link_to "投稿する", new_post_path, class: "btn btn-primary btn-lg btn-record" %></p>
      <div class="col-md-12">
        <h3 class="post-title">ユーザーの投稿 (<%= @feed_items.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>    
<% else %>
    <div id="carousel-2" class="carousel slide carousel-fade" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#carousel-2" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-2" data-slide-to="1"></li>
    </ol>
    <div id="title-image" class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <%= image_tag asset_path("family.jpg", alt: "responsive image"), class: "d-block image-fluid w-100" %>
            <h1>育児・妊娠について悩みはありませんか？</h2>
            <p>ここはそういう悩みをみんなで解決するコミュニティーです</p>
        </div>
        <div class="carousel-item">
            <%= image_tag asset_path("baby.jpg", alt: "responsive image"), class: "d-block image-fluid w-100" %>
            <h1>一人で抱え込むのはやめましょう</h1>
            <p>聞きたいことや気になっていることを"チルシェア"しよう</p>
        </div>
    </div>
    </div>
    <div class="help">
        <h3>Chi-Shaとは？</h3>
        <p>育児共有<p> 
        <h1><span>Chi</span>ldcare<span>Sha</span>ring</h1>
        <div class="flex">
            <div class="img-item">
                <p class="description">育児中、または妊娠中は悩みがいっぱい。<br>
                「赤ちゃんの効果的な寝かしつけ方は？」<br>
                「陣痛が始まった時どうするんだろう？」<br>
                「赤ちゃんが泣き止むみんなのおすすめな曲は？」<br>
                こういった悩みや疑問を,<br>
                ネットで探しても欲しい答えが見つからない。<br>
                実体験をふまえた解決方法を知りたい。<br>
                そういった悩みを"Chi-Sha"で共有してみませんか？
                </p>
            </div>
            <div class="img-item">
                <%= image_tag asset_path("description.jpg"), class: "rounded-circle" %>
            </div>
        </div>
    </div>
    <div class="make">
        <h1>Chi-Shaの使い方</h1>
        <div class="feature-list">
            <div class="feature-item">
                <%= image_tag asset_path("see.jpg"), height: "300px" %>
                <h2>オススメのものや悩みを検索して見る</h2>
                <p>みんなのオススメのもの・こと<br>
                自分が抱えている悩み疑問を検索して<br>
                ユーザーの投稿から調べて見る</p>
            </div>
            <div class="feature-item">
                <%= image_tag asset_path("hear.jpg"), height: "300px" %>
                <h2>悩みを聞く</h2>
                <p>自分が抱えている悩みや疑問を<br>
                コメントして聞いてみる</p>
            </div>
            <div class="feature-item">
                <%= image_tag asset_path("answer.jpg"), height: "300px" %>
                <h2>オススメのものを教える</h2>
                <p>育児でオススメのもの・ことを<br>
                みんなで共有する</p>
            </div>
    </div>
    </div>
    <div class="go">
        <%= link_to "Chi-Shaを始める", signup_path, class: "btn btn-primary" %>
    </div>
<% end %>