config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get :help, to: 'static_pages#help'
  get :signup, to: 'users#new'
  get :problem_search, to: 'problems#problem_search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :likes, to: 'likes#index'
  post   "likes/:post_id/create"  => "likes#create"
  delete "likes/:post_id/destroy" => "likes#destroy"
  resources :comments, only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :messages
    end
  end
  resources :messages,            only: [:create, :destroy]
  resources :notifications, only: :index
  resources :problems
  resources :problem_comments, only: [:create, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :logged_in_user

  def index
    @likes = current_user.likes
  end

  def create
    @post = Post.find(params[:post_id])
    @user = @post.user
    current_user.like(@post)
    @post.create_notification_like!(current_user)
    respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    current_user.likes.find_by(post_id: @post.id).destroy
    respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% @post = Post.find(like.post_id) %>
<% user = @post.user %>
<li id="like-<%= like.id %>">
  <div class="row like-post">
    <div class="col-md-10 post-md">
      <p class="post-like-title"><%= link_to @post.title, post_path(@post) %></p>
      <p class="post-like-description"><%= text_url_to_link(h(@post.description)).html_safe %></p>
      <div class="col-md-6">
        <%= link_to((image_tag @post.picture.thumb400.url), post_path(@post), class: 'post-like-picture') if @post.picture.url.present? %>
      </div>
      <p class="likes-user">投稿ユーザー： <%= link_to user.name, user_path(user) %></p>
    </div>
  </div>
</li>

app/views/likes/create.js.erb
$("#like-<%= @post.id %>").html("<%= escape_javascript(render('users/unlike')) %>");

app/views/likes/destroy.js.erb
$("#like-<%= @post.id %>").html("<%= escape_javascript(render('users/like')) %>");

app/views/likes/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h3> いいね (<%= @likes.count %>)</h3>
    </div>
  </div>
  <% if @likes.present? %>
    <ol class="likes">
      <%= render @likes %>
    </ol>
  <% end %>
</div>