config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get :help, to: 'static_pages#help'
  get :signup, to: 'users#new'
  get :problem_search, to: 'problems#problem_search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  resources :relationships, only: [:create, :destroy]
  get :likes, to: 'likes#index'
  post   "likes/:post_id/create"  => "likes#create"
  delete "likes/:post_id/destroy" => "likes#destroy"
  resources :comments, only: [:create, :destroy]
  resources :talks,               only: [:show, :create] do
    member do
      post  :memberships, :messages
    end
  end
  resources :messages,            only: [:create, :destroy]
  resources :notifications, only: :index
  resources :problems
  resources :problem_comments, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items %>
<% end %>

app/views/shared/_feed_problem.html.erb
<% if @feed_problem_items.any? %>
  <ol class="posts">
    <%= render @feed_problem_items %>
  </ol>
  <%= paginate @feed_problem_items %>
<% end %>

app/views/shared/_recruit_login.html.erb
<div class="requruit-block">
  <div class="signup-group">
    <h3 class=title-form>【採用担当者様 専用ログインフォーム】</h3>
    <h4 class="description-form">下記の「専用ログイン」ボタンを押していただければ、<br>すぐに専用アカウントでログインが可能です。</h4>
    <%= form_for(:session, url: login_path, local: true) do |f| %>
      <div class="field"> 
        <%= f.label :email, "メールアドレス" %>
        <%= f.email_field :email, class: "form-control", id: "requruit_email", value: 'saiyou@example.com' %>
      </div>
      <div class="field"> 
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control", id: "requruit_password", value: 'password' %>
      </div>
      <%= f.label :remember_me, class: "checkbox inline requruit" do %>
        <%= f.check_box :remember_me %>
        <span>ログインしたままにする</span>
      <% end %>
      <div class="actions">
        <%= f.submit "専用ログイン", class: "btn btn-primary btn-requruit" %>
      </div>
    <% end %>
    <div class="recruit-account">
      <p>＜採用担当者様 専用アカウント＞</p>
      <p>メールアドレス：saiyou@example.com</p>
      <p>パスワード：password</p>
      <p>※フォームに予め入力済です</p>
    </div>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat"><%= @user.following.count %></strong><span class="follow-color">人をフォロー</span></a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat"><%= @user.followers.count %></strong><span class="follow-color">人のフォロワー</span></a>
</div>